### ISSUE TITLE
Alignment between grey scale image depth mask

### ISSUE THREAD

**Issue by Sean0120** [better-flow/evimo#10]
Hi,
    I just have check on the depth mask you provided in the dataset. And i found that for some images, the greyscale image and the depth mask are misaligned just as shown in the attached images. Is there any update in the data or do you have any method to reduce the misalignment?

Thanks for your attention and help.

![Figure_1](https://user-images.githubusercontent.com/32014802/97449011-31f16c80-196c-11eb-85f7-72026bea97eb.png)
![Figure_1-1](https://user-images.githubusercontent.com/32014802/97449016-33bb3000-196c-11eb-8b2a-3f8f7f2620de.png)
![Figure_1-6](https://user-images.githubusercontent.com/32014802/97449020-3453c680-196c-11eb-8e47-c30404636a40.png)

**Comment by ncos** [comment]
1) During fast motion the framerate of grayscale images might affect the alignment of depth - since depth is generated on the basis or Vicon, and the tool just picks the nearest frame to the timestamp. Could you check the depth-to-event alignment in these timestamps?

2) It *is* possible that time alignment parameter is incorrect; I thought I checked everything but try adjusting sliders (in the offline tool) - they control calibration and temporal alignemnt. We are working on a new dataset, with a much better calibration (hopefully) - feel free to e-mail at amitrokh@umd.edu if you would like me to send you some early recordings!

**Comment by Sean0120** [comment]
Thanks for your reply!
