### ISSUE TITLE
Object Pose and Camera Pose don't seem to be aligned?

### ISSUE THREAD

**Issue by alexisbdr** [better-flow/evimo#11]
Hi, 

I'd like to understand why you represent the camera pose w.r.t to the initial pose p0 as done here:
https://github.com/better-flow/evimo/blob/967d4d688ecee08e0c66b0c86c991980434e6c41/evimo/dataset_frame.h#L278
By doing so it seems like the poses of the object and camera inside meta.txt are not in the same frame of reference and not using the same coordinate system. 

I'm trying to use the object and camera pose to render inside a 3D environment. Thank you for your help.

**Comment by alexisbdr** [comment]
Hi, 

I found that the object pose is actually transformed to the camera frame as done here:
https://github.com/better-flow/evimo/blob/967d4d688ecee08e0c66b0c86c991980434e6c41/evimo/dataset_frame.h#L184

Could you explain why you do this?

Also would you happen to know what coordinate system reference frame you use (ENU / NED) because no matter what I try it does not work. 

Thanks for your help

**Comment by ncos** [comment]
Hi @alexisbdr, sorry for taking so long with the reply; 
Can I ask you - is there any reason why you do not use the output of the pipeline? Since it has trajectories already (see [here](https://github.com/better-flow/evimo/wiki/Ground-Truth-Generation)). The rotation there is a quaternion, so should be well defined.

Our goal was to move independent objects to camera frame, to project 3D on the camera plane and generate ground truth masks. Hence that function!

I would really suggest using the output (i.e. - the dataset), and not the raw code. Although, given that we were able to generate correct masks I assume that our coordinate frames are correct; I am not sure diving in the code is worth the effort)

Another advise - since you seem to need trajectories in the world frame, why do not you use the .bag files we provide and just replay Vicon trajectories?
