### ISSUE TITLE
Bad data in EVIMO2v2

### ISSUE THREAD

**Issue by danqu130** [better-flow/evimo#18]
Thanks for the opensourced new dataset first and foremost!
Using the provided interactive visualizer, I found some bad data. Are these normal?

The following example is scene9_dyn_train_02_000000 sequence, the depth map is discontinuous and does not correspond to events and image.
![image](https://user-images.githubusercontent.com/15975091/168824492-9e54058e-67dc-4761-93c4-b3cf678fd6f2.png)
![image](https://user-images.githubusercontent.com/15975091/168824590-47962fbc-0456-410f-93d0-23372bd5e8af.png)
![image](https://user-images.githubusercontent.com/15975091/168824717-f15ec04f-2611-48d2-99c2-8bbbfa2a8e2f.png)

**Comment by aftersomemath** [comment]
Hi thanks for pointing this out.

Discontinuous, depth and object pose happens occasionally. It happens when the Vicon motion capture system incorrectly reports an objects pose or location for a few samples.

These periods of discontinuous motion should be short enough to not "ruin" any particular sequence. We did manual review and some automatic filtering to detect and remove egregious instances. If you find any sequences with lengthy periods of mis-reported of object pose (and depth), please let us know.
