### ISSUE TITLE
Polarity of EVIMO2v2_MS_Samsung_mono's events 

### ISSUE THREAD

**Issue by moonflo** [better-flow/evimo#20]
Hello, thanks for your great work. I'm doing some simple research based on this dataset recently and found that unlike other event-based datasets, the timestamps of EVIMO2v2_MS_Samsung_mono's events are always appear in groups intermittently, and the event's polarity is not -1 and 1, but a bunch of 0, 1, 2, 3... . I would like to ask if this format has its unique meaning? How should I handle the information on the polarity dimension?

Thanks for your help.

**Comment by aftersomemath** [comment]
Thanks for your comment, I just became aware of it and will look into this soon.

**Comment by aftersomemath** [comment]
Thank you very much for making this issue.

The timestamp grouping appears to have occurred at the camera driver level because the groups are present in the raw ROS bag recordings. It is possible this grouping is actually do to hardware limitations, however I don't know enough to know for sure. Regardless, because the groups are in the raw recordings, there is nothing that can be done. I have calculated some statistics that provide more insight.

The event polarity issue is a bug in the NPZ format generation. **To fix it, the NPZ version of the dataset will be regenerated and uploaded within the next two days.**

## Timestamp grouping

The grouping of events at particular timestamps occurs in the raw ROS bag recordings. There is grouping in both the Prophesee and the Samsung event streams however the grouping is much more noticeable in the Samsung event stream. The sorted, per-sequence average and median timestamp group interval is shown below on a per-camera basis. I believe the stair stepping in the median plot further suggests the limitation is at the driver or hardware level.

The code used to generate the timestamp grouping results is in df6fa80a02046c085c441b1bcc767c75f703312f.

### Median
![Figure_5](https://user-images.githubusercontent.com/6125615/169895841-d659adaf-1df9-4713-b56d-967693140a8c.png)

### Average
![Figure_3](https://user-images.githubusercontent.com/6125615/169895943-348647a3-b495-46ce-b26c-8add2928b515.png)

## Polarity

A typo in the NPZ generation pipeline caused an array to be incorrectly indexed. The event "polarities" in the NPZ version of EVIMO2 are the events timestamp converted to a `uint8`. All event streams in the NPZ format are affected. The TXT format is not affected. The buggy line of code is [here](https://github.com/better-flow/pydvs/blob/90c88249f82a0b7764587611ae22f97127aa7659/samples/evimo-gen.py#L363).

**Comment by moonflo** [comment]
That's a lot of help, thanks.

**Comment by aftersomemath** [comment]
The NPZ version of the dataset has been reuploaded with fixed event polarity.

One caveat is that the Samsung's event polarity appears to be inverted when compared to the Prophesee camera's. This inversion appears to have happened at the driver level since otherwise the code paths are identical. This has been noted in the documentation.
