### ISSUE TITLE
Optical flow of evimo2v2

### ISSUE THREAD

**Issue by moonflo** [better-flow/evimo#21]
Hello, sorry to bother you, but when I run the tool (evimo_flow.py) to generate optical flow, I found that although the direction of the optical flow is correct, there is some problem with the magnitude of its modulus.

![image](https://user-images.githubusercontent.com/90757878/170180496-f94c3321-c8c2-41a6-b39b-d7845c2eac0a.png)

As shown in the image above, I used your tool to visualize scene9_train_1 sequence's optical flow and found some issues with the length of the arrows representing the optical flow.
When I take out a  array slice corresponding to flow13.png's optical flow and print it, its output also shows that the size of this value is abnormal.

![image](https://user-images.githubusercontent.com/90757878/170181072-d338fb49-46d0-4a99-b846-085fb4664d83.png)

I'm not sure if I'm doing something wrong or there's some bug in this tool, the instruction I use to generate the optical flow is:
`python3 evimo_flow.py scene9_dyn_train_01_000000 --dframes 3 --format evimo2v2 --quiet --overwrite`

I'm rechecking to see if there's a problem with my operation, if you know at which step I'm going wrong, I'd appreciate it if you could help me point it out.

**Comment by aftersomemath** [comment]
Thanks for reporting this issue!

It appears the `dframes` flag is horribly broken in that script (in fact it's throwing exceptions in two places for me on that sequence). The `dframes` flag was meant for debugging and it looks like I seriously messed it up when revamping the script for EVIMO2v2. I'll fix the script tomorrow.

I wanted to ask, is there a reason why the `dframes` flag is desired instead of `dt`? The depth frames are not evenly spaced in time because depth is not always available. So using `dframes == 3` will usually result in flow approximated with finite difference over a 3/60 ~= 48 ms window. However, if depth is missing for a few frames, that window will unexpectedly become much larger and then shrink again.

**Comment by moonflo** [comment]
Thanks for such a quick reply. My original idea was to divide the complete event packet into 20Hz event packets based on the depth frame flag, and then read one event packet at a time in my work. I want to align the optical flow and the depth frame in quantity, so that the alignment of events and optical flow can be achieved. But now it seems that this may not be a good idea.
I'll change my strategy and try to use the `dt` flag, thanks again for your inspiring reply.

**Comment by aftersomemath** [comment]
I think the fastest way to achieve that _right now_ would be to set `dt` to `0.050` and then delete (or ignore) two out of every three generated flow fields and two out of every three depth maps.

I like the idea of being able to control the interval between flow fields independently of the time window used for finite difference. I might end up adding a flag for that tomorrow while I'm at it.

**Comment by moonflo** [comment]
Thank you very much for your advice and efforts, it helped me a lot. You are so kind, sir.
