### ISSUE TITLE
Problem with data download

### ISSUE THREAD

**Issue by Sean0120** [better-flow/evimo#22]
Hi,
Thanks for the great data you provide.
It seems that the server is not stable. While downloading the ROSBAG, it keeps saying that "failed, unknown server error".
In the beginning, everything goes well. But after several minutes, the download speed goes to zero but no further response.
I have tried on several computers under different internet connections but get the same result.

Are there any other stable ways to download the data?
Thanks for your attention and help.

**Comment by aftersomemath** [comment]
Hi,

Thanks for bringing up this issue!

I think this may be due to a long distance internet connection and the size of the files. I tested downloading the dataset before and did not have any errors (of course things could have changed).

If you haven't tried this already, one option is to see if a download manager that can resume failed downloads solves the problem. For example this browser extension:

https://chrome.google.com/webstore/detail/turbo-download-manager-3r/pabnknalmhfecdheflmcaehlepmhjlaa?hl=en

I know there is also standalone software to do the same thing.

If this type of software is unable to solve the problem I will look into alternatives.

**Comment by Sean0120** [comment]
Hi,
Thanks for the methods you provided.
I have tried them both but the result is the same as before. 
The download stops at certain points. Even if I pause and resume, there is still no further progress.
As for the download script, the transmit also stops at certain points.

Maybe we need some alternatives.

**Comment by aftersomemath** [comment]
Hi,

I just tried the browser extension this morning and it did not work for me either. I simulated an unstable internet connection by unplugging my router and afterwards pause and resume did not work.

However, [kget](https://apps.kde.org/kget/) did work. After unplugging/replugging my router `kget` was able to resume the download. (`sudo apt install kget` to install).

The alternative is probably uploading to Google Drive. Unfortunately, google drive may have the same problem if the internet connection is unstable. If you are willing, could you give `kget` a try?

If it does not work I will look into Google Drive.

**Comment by Sean0120** [comment]
Hi, thanks for your advice.
kget works and I get successfully the data.
Thanks!!
