### ISSUE TITLE
How to extract background depth for EVIMO

### ISSUE THREAD

**Issue by rwn17** [better-flow/evimo#23]
Hello thanks for your question. Low resolution depth is available in the background for the original EVIMO dataset. However, background depth is not available for the EVIMO2 dataset.

The website has been recently updated to make the difference more clear.

_Originally posted by @aftersomemath in https://github.com/better-flow/evimo/issues/14#issuecomment-1025221555_

Thanks for your great work! I was wondering where can I find this "low-resolution depth for background"? I check the npz type file and raw rosbag and didn't find it. Thanks in advance!

**Comment by aftersomemath** [comment]
Hi,

It is my understanding that in EVIMO1 the pixels that correspond to the background have depth available in the depth images. There is no separate source of depth for the background, all depth comes from the depth images in the generated dataset.

In EVIMO2 the pixels corresponding to the background do not have depth available (they are set to 0 if I remember correctly).

Hopefully that helps, please let me know if something seems wrong!

**Comment by rwn17** [comment]
Hi, 

Thanks for your prompt reply! But in the depth_mask_ID.png file, I cannot find the depth for the background(same for npz format file). Here is how I read it.

![Screenshot from 2022-09-29 11-27-24](https://user-images.githubusercontent.com/54616858/192995254-87aa1227-daba-4c16-a329-eafd2889edc5.png)

Looking forward to your reply

**Comment by aftersomemath** [comment]
Thanks for persisting!

I went and checked the released data for EVIMO1. You are correct, depth is not present for the background pixels.

I checked with the creator of EVIMO1 and it turns out background depth is available, but you have to regenerate the EVIMO1 data. The background depth is "not accurate", which is why it was not included in the generated data.

The website and documentation will be updated accordingly and I'll update this thread when it is. Many apologies for the wasted time...

While I am not sure how accurate background depth needs to be for your application, I think it should be mentioned that the background depth probably will not be very good. The scanning methods are very different for a room versus a small object. If you are training a deep learning architecture or evaluating a classical algorithm, it may be preferable to just train on EVIMO2 and only calculate the loss on the pixels where depth is available. We are working hard to find a good way to get background depth for EVIMO3.

**Comment by aftersomemath** [comment]
Hi,

To regenerate EVIMO1 with background depth you should:

- Checkout the `evimo1` branch [here](https://github.com/better-flow/evimo/tree/evimo1)
- Rerun the generator tool with the `_no_bg` flag set to false. [Here](https://github.com/better-flow/evimo/tree/evimo1#run-the-data-generation) is an example with the `_no_bg` flag set to true.

Again while I am not sure of your application, I have been told the background depth in EVIMO1 is quite poor. So it seems likely that this route might be more work than it is worth.
