### ISSUE TITLE
some uncommon values in flow_GT

### ISSUE THREAD

**Issue by HTLeoo** [better-flow/evimo#28]
Hi, sorry to bother you again.
I found an interesting thing when I use generated flow_gt. The data type of flow_gt is 'float32' by default. I notice that the value in x or y channel sometimes increases to thousands (in my example, dt=0.05), and this causes a 'RuntimeWarning: overflow encountered in multiply' when I check the magnitude using 'numpy.linalg.norm' function. I guess the extremely large flow value is the main cause. Sometimes it will corrupt the evaluation results (end-point-error uses L-2 norm) on whole eval sequences (I use whole sfm eval sequences).
I have to admit that I just mask the 'nan' and 'inf'  and constrain the absolute values of both x, y channels bigger than zero (regular mask in MVSEC dataset), and I found this problem by looking at each sequence.
Is it convenient for you to give an official script to avoid this (like DSEC-Flow)？

**Comment by aftersomemath** [comment]
Yes, this definitely needs to be fixed. Thanks for letting me know.

Can you tell me a specific sequence where this is happening? I will reproduce the problem and find a fix.

**Comment by HTLeoo** [comment]
Sure, I look back at the sequences (left event camera with VGA resolution).
In 'sfm/eval/scene_03_00_000000' ,  at least one flow magnitude exceeds 1500.
In 'sfm/eval/scene_03_01_000000' , some flow magnitudes exceed 2000.
I haven't looked at others, because I changed my mask to filter out the flows whose magnitudes are bigger than 500 (just for convenience). But I believe that more sequences should be checked.

**Comment by aftersomemath** [comment]
Thanks for reporting this!

aa1fcaa82613e1617051f268c4483ce807ba0ce9 fixes this issue and introduces a new script, `evimo_flow_statistics.py`, to calculate a histogram of flow X-Y displacements in order to be sure the issue is fixed.

The problem was that the motion capture system occasionally loses track of the objects and reports an incorrect position or orientations that appear as a "jump" in the position or orientation. So, have added a check to `evimo_flow.py` for very high linear or angular velocity. If an object's trajectory "jumps" then the flow pixels associated are set to NaN like the background pixels.

Before this fix there were occasionally very high values in the flow field (>1000 and I saw one on the order of 1e23). After this fix the flow values are much more reasonable (< ~250 at 60 fps, which is possible for very fast motions close to the camera as in the sanity sequences). Below is are histograms calculated with the new `evimo_flow_statistics.py` for each camera:

## Left Prophesee
![flow_test_all_after_left_8](https://user-images.githubusercontent.com/6125615/234951583-e90f775d-26c1-4945-91d7-6b965313d281.png)

## Right Prophesee
![flow_test_all_after_right_8](https://user-images.githubusercontent.com/6125615/234951646-89961728-af79-459f-b519-584ee35a012d.png)

## Samsung
![flow_test_all_after_samsung_8](https://user-images.githubusercontent.com/6125615/234951682-ad7897ac-428f-41a3-a6b6-1bd4f2cfa9f8.png)
