### ISSUE TITLE
Velocity of objects missing in meta.txt

### ISSUE THREAD

**Issue by sam575** [better-flow/evimo#5]
The velocity of objects was missing in the dataset provided, so I looked into the code and found that the following lines [164](https://github.com/better-flow/evimo/blob/evimo2/evimo/dataset_frame.h#L164) and [269](https://github.com/better-flow/evimo/blob/evimo2/evimo/dataset_frame.h#L269) are commented. As I notice a TODO there, I want to know if accurate velocity of objects can be generated by uncommenting these lines?

**Comment by ncos** [comment]
If you require instantaneous velocity (not a frame-to-frame transform), I advise you to fit the splines to motion data and take derivatives (numpy has this functionality) - otherwise you will suffer from noise (even Vicon has some!). That C++ code was not reliable in this sense, so I would not recommend you to use it.

For transforms some filtering might be required, depending on the amount of actual motion between frames - I suggest you use the [pyquaternion](http://kieranwynn.github.io/pyquaternion/) and .npz format to compute inverses of transformations and then - transforms between frames in the coordinate frame of your choice.
