### ISSUE TITLE
Could you please a DETALED introduction on how to use this dataset?

### ISSUE THREAD

**Issue by Ethan-Zhou** [better-flow/evimo#8]
Hi, 

I have problems with using this dataset. Can you provide a detailed introduction on

1) Installation. (what dependencies are necessary and where can users find them, e.g. the vicon package, what is that?)
2) How to generate pixel-wise object labelling groundtruth?
3) Which branch to use, master or the other one?

Many thanks,

Joey

**Comment by ncos** [comment]
Hi!

In order to use the dataset you do not need to install anything - download the data in the .txt format from the [website](https://better-flow.github.io/evimo/downloads.html) - it will have grayscale images, masks and event.txt with events. Note that we do not include the background depth (only depth for moving objects)!

1. For vicon, see [this](https://github.com/better-flow/evimo/issues/2#issuecomment-650910334)
2. Data regeneration is by no means user-friendly, so I suggest you use the .txt or .npy data format from the released data. Take a look [here](https://github.com/better-flow/evimo/issues/3) to get an idea on how to parse the data. A sample command to generate data is given in the README.md. You would need to download the raw bag files from the website.
3. For the released dataset use the master branch - the other one is not compatible with the format (although I might convert the data in the future and merge evimo2 in master).
