### ISSUE TITLE
What is the meaning of parameters in calib.txt

### ISSUE THREAD

**Issue by Sean0120** [better-flow/evimo#9]
Hi,
    I just have a check on the calib.txt, the calibration parameters you provided. What's the meaning of the these 8 parameters?
In the code you,provided i see two methods to use them.
    1. In online.cpp file, the undistort function directly feed the distort parameter into OPENCV function, Here the meaning of these 4 parameters are k1 k2 p1 p2 following the naming in OPENCV.
    2. in online.cpp project_point function, you use them as k1 k2 k3 k4.
I am quite confused about what is the exactly meaning of the parameters. 
By the way, in the undistort function, cv::undistort(img, ret, K, D, 0.87 * K) line, you have a constant 0.87. Why we need a constant here?

thanks for your attention and help.

**Comment by ncos** [comment]
There are 2 files actually: 
1) calib.txt contains intrinsic parameters (fx, fy, cx, cy, k1, k2, k3, k4) - as you mentioned, this is directly fed to opencv's undistort. Sorry for the confusing names: k3 and k4 should correspond to p1 and p2 in OpenCV's terms.
2) The extrinsics.txt has camera extrinsics - its location in respect to Vicon coordinate frame.

I am currently working on evimo2 (with new recordings, 640x480 event cameras and way more objects) - I will merge the 'evimo2' branch in master and convert the evimo1 dataset (the format has changed a bit). Hopefully, there will be fewer issues like that!

*Now, what you point out looks like a bug.* In the 3d project point functions only apply the radial distortion, and use tangential params as additional radial parameters; it does not look like the result is affected by much - since k3/4 are very small, and the field of view of the camera is small as well. This issue is fixed in the [new version](https://github.com/better-flow/evimo/blob/0779e13bd35117c3635e8e34e11fc2eb6526e1f2/evimo/dataset.h#L611). I will double check, and try to fix asap, but I feel like the quickest way (and the closest to the current state) is to zero out k3 and k4 in the calib.txt.

Also please note that the 'offline.cpp' is the main dataset generation code, while 'online.cpp' is for visualization only.

**Comment by Sean0120** [comment]
Got it, Thanks
